### ISSUE TITLE
Trouble programming the nrf52382 chip...

### ISSUE THREAD

**Issue by sleepiestdave** [pyjamasam/DIYDragy#1]
Hi!  Forgive me as this is my first delve into these types of software.  I have the hardware part built and operating, but I have not been able to get it coded.  I downloaded Segger and was wondering if you could offer some pointers or direction?  
Do I need a jlink or a DK board in order to program? 
Thanks for your time regardless!
David

**Comment by pyjamasam** [comment]
WOW.  Somebody is actually playing with this :-).  Sweet.

So I ended up buying a DK board (one to help me write the code, and two to make the install easier on the real board).  But in the end I think a cheap jlink programmer will do as well.

 I ended up making a cable (like this one - https://devzone.nordicsemi.com/attachment/e417459405c7675236d8842c0015b72f) to do my flashing.

SCK and SDO are labeled on the BLE board, and then VCC and GND are the other connections (that are labeled as well).

When the DK sees the GND Detect it programs the external chip vs the internal one.

Hope that helps.  Let me know if you run into anything else.

**Comment by sleepiestdave** [comment]
Heck yeah man!  Really was excited to find your Tesla post and then all of this!  Figured what better way to get more involved with BLE and software meshing (ios app data pulling, etc).  

Do you know if this cable would work as a DK?   
https://www.sparkfun.com/products/15345
I can grab that right down the road if so!  

Barring that, they also have:
https://www.sparkfun.com/products/15025 (Can I use a 840 board to program an 832?)
or do I need to use an FTDI breakout and this:
https://www.sparkfun.com/products/13990

Forgive the simple questions please :)
I'll talk with Sparkfun tomorrow to see if they can help me understand as well. 

Really appreciate any and all help man!  Very excited for this!

**Comment by pyjamasam** [comment]
So the j-link edu might work.  It has the SWDIO SWCLK pins that are needed.  Also looking through a lot of the documentation for it there is a lot of references for Segger stuff.  So thats encouraging.

I don't know if the nRF52840 board will work.  It's a different chip and I don't know enough to know if it's compatible.

The nRF52832 board is actually just the same as the board you already have.  It just has broken out more of the pins.  There isn't any of the programming circuitry.

As far as I know you can't program these chips serially (like with a FTDI like an arduino).  So I think in this situation the j-link board is your best bet.

**Comment by sleepiestdave** [comment]
Awesome, really appreciate the follow up!  Thank you for clarifying!  Sparkfun said the same, going to grab that jlink cable over the weekend!

**Comment by pyjamasam** [comment]
Sweet.

Looking forward to hearing how things go with it.

**Comment by sleepiestdave** [comment]
Hey!  So I finally got my cable setup (long story) and can program the chip finally.  I am using the edu mini and it does work.  

However, I am still very lost as to the software end on this.  

I tried to compile the DIYDragy.emProject once I replaced the path name and got two errors:
<img width="777" alt="Screen Shot 2020-10-10 at 5 41 21 PM" src="https://user-images.githubusercontent.com/72054615/95667196-dfb4ec80-0b1f-11eb-9111-24246c8fce36.png">

I don't suppose you'd be willing to do a little more hand holding?  No worries if not.

I can connect to the device via Jlink, but I have yet to be able to get it to show up on any bluetooth scanner?  

I definitely went in over my head on this and it shows, haha.  

Thanks regardless for your time and efforts!

**Comment by pyjamasam** [comment]
Hmm...  That seems like a build problem in Segger.  What version of Segger are you using?  I can see if I can try to get it building.  I haven't installed stuff on my new laptop so its a good test bed to see whats up.

**Comment by Nexetion** [comment]
@pyjamasam is there any other place to buy all the components other then aliexpress? not trying to wait two-three months for all the parts.

**Comment by pyjamasam** [comment]
> @pyjamasam is there any other place to buy all the components other then aliexpress? not trying to wait two-three months for all the parts.

Doing some quick googling it looks like a bunch of the parts are available in from different suppliers.  The big keys are the ublox compatible 10hz gps and the BLE board thats a nRF52832 chip.  

I was going for cheap alternatives when I was initially building stuff, so waiting for aliexpress was the way I went.  If you are ok with spending a little more there are options I am sure.

**Comment by Nexetion** [comment]
https://www.digikey.com/en/products/detail/sparkfun-electronics/GPS-15210/10064422?utm_adgroup=Evaluation%20Boards%20-%20Expansion%20Boards%2C%20Daughter%20Cards&utm_source=google&utm_medium=cpc&utm_campaign=Shopping_Product_Development%20Boards%2C%20Kits%2C%20Programmers&utm_term=&utm_content=Evaluation%20Boards%20-%20Expansion%20Boards%2C%20Daughter%20Cards&gclid=CjwKCAjw0On8BRAgEiwAincsHNUN898rdEa2mT1czIcJ6fTx99HSTzbhkix17GfPKpeuLWxKKHb07BoCI3UQAvD_BwE

https://www.adafruit.com/product/3406

will these work?

I don't see the VDD out on these boards? Also don't see Pin out 6 or 8 on the BLE board. If the GPS has the 3.3v out then do I still need the regulator?

**Comment by pyjamasam** [comment]
GPS looks fine.  It says it supports UBX binary output as well as 10HZ (looks like even 18HZ with only a single satellite constellation).

The adafruit board is the right chipset, and it has the pins needed exposed (tx/rx) as well as a charge controller, and voltage regulator.

The downside is that I don't know if the code for the nRF board that is posted in this repo will be easily loadable.  Adafruit's board has a bootloader loaded that lets you serially program the board using the arduino toolsets.  That actually makes it easier slightly.  But you'll more then likely have to re-write the board firmware based off of the example they provide (https://learn.adafruit.com/bluefruit-nrf52-feather-learning-guide/ble-uart-controller).

The board firmware is really just a BLE to UART bridge.  There isn't any smarts with regards to speed and launches and anything else.  All that is done in the iOS app.  So it's all technically possible.  But it will require work. 

This board (https://www.adafruit.com/product/4077) is closer to the board I had listed in the BOM.  But it required an external programmer and then all the battery and voltage stuff.  But it would be a drop in with regards to the code posted in this repository.

OHHH.  As I read more you can put a header in the middle of the feather board that will expose the SWD programming pins...  That suddenly makes it possible to use the same external j-link programmer (https://www.adafruit.com/product/3571) to program it with my code here.  So maybe thats a good option.  Makes all the power stuff easier to work with since its all on board, and then you just need a board and programmer and GPS.

Hopefully this all helps.  I have been kinda rambling.  Sorry.

**Comment by pyjamasam** [comment]
Its been a while with no updates....  Closing this

**Comment by yarodevuci** [comment]
@sleepiestdave were you able to figure things out?

**Comment by yarodevuci** [comment]
@sleepiestdave are you able to upload diagram how you managed to connect Jlink to BLE?

**Comment by yarodevuci** [comment]
> e417459405c7675236d8842c0015b72f I ended up making a cable (like this one - https://devzone.nordicsemi.com/attachment/e417459405c7675236d8842c0015b72f) to do my flashing.

Link no longer works(

**Comment by pyjamasam** [comment]
https://devzone.nordicsemi.com/f/nordic-q-a/14058/external-programming-using-nrf52-dk
